run-name: Run unittests for api by ${{ github.actor }}

on:
  push:
    branches: main

jobs:
  run-unittests:
    strategy:
      fail-fast: false
      python-version: "3.12"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ python-version }}
      - name: Install dependencies
        run: |
          python -m pip --upgrade pip
          pip install -r api/requirements.txt
      - name: Test with Pytest
        run: pytest -vv
        working-directory: api