run-name: Run unittests for api by ${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - "api/**/*.py"

jobs:
  run-unittests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r api/requirements.txt
      - name: Test with Pytest
        run: pytest -vv
        working-directory: api