run-name: Run tests for api by ${{ github.actor }}

on:
  - push
  - workflow_dispatch

jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: api
      - name: Test with Pytest
        run: pytest -vv
        working-directory: api/test/unittests
  
  run-dal-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Test with Docker compose
        working-directory: api/test/integration
        run: |
          docker compose up --abort-on-container-exit